services:
  php-env:
    build:
      context: .  
      dockerfile: Dockerfile 
    volumes:
      - ./src:/var/www/html
      - ./vendor:/var/www/html/vendor
    ports:
      - 9003:80 # Tällä osoitteella otetaan yhteys selaimella
    depends_on:
      - mysql_db
    env_file:
      - .env
    environment:
      - DEBUG_ENV=true
  mysql_db:
    image: mysql:8.3 # latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 9004:80
    environment:
      PMA_ARBITRARY: 1  
    depends_on:
      - mysql_db